# Generated by Django 4.2 on 2023-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='adresss',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='phoneee',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='product_nameee',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='sizeee',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='login',
            name='usernameee',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
