# Generated by Django 4.1.6 on 2023-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='adress',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
