# Generated by Django 4.1.6 on 2023-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_login_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='product_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
