# Generated by Django 4.1.6 on 2023-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login_phone_login_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
