# Generated by Django 4.1.6 on 2023-04-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_login_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
    ]
