# Generated by Django 4.1.6 on 2023-04-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='pricee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
