# Generated by Django 4.2 on 2023-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_destination_pricee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='des',
            field=models.CharField(choices=[('OR', 'Original'), ('MI', 'Mirror')], max_length=2),
        ),
    ]
