# Generated by Django 4.2 on 2023-04-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_alter_destination_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='des',
            field=models.CharField(choices=[('OR', 'Original'), ('MI', 'Mirror'), ('EG', 'Egyptian')], max_length=2),
        ),
    ]
