# Generated by Django 4.2 on 2023-04-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_destination_img_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img1',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img2',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
