# Generated by Django 4.2 on 2023-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0007_destination_img1_destination_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img2',
        ),
        migrations.AlterField(
            model_name='destination',
            name='img1',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
