# Generated by Django 4.2 on 2023-04-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_remove_destination_img2_alter_destination_img1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img1',
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
