# Generated by Django 4.2 on 2023-04-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0010_destination_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='des',
            field=models.CharField(choices=[('OR', 'Original'), ('MI', 'Mirror'), ('EG', 'Egyptian'), ('SH', 'SHIRTS')], max_length=2),
        ),
    ]
