# Generated by Django 4.2 on 2023-04-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0013_remove_destination_payability'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='payability',
            field=models.CharField(choices=[('PY', 'PAYNOW'), ('NPY', 'NOT')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
