# Generated by Django 4.2 on 2023-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0018_alter_destination_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='later',
            field=models.BooleanField(default=False),
        ),
    ]
